import Head from 'next/head'
import React, { useState } from 'react';
import styles from '../styles/Home.module.css'

export async function getServerSideProps(){
  const res = await fetch("https://jsonplaceholder.typicode.com/todos");
  const data = await res.json();

  return{
    props:{
      todos: data
    }
  }
}

export default function Home({ todos }) {

  return (
    <div className={styles.container}>
      <Head>
        <title>NEXTJS SSR Sample</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        NEXTJS SSR Sample
      </h1>

      <a
        href='https://github.com/thutasann/nextjs-ssr-sample'
        target="_blank"
        rel="noreferrer"
        style={{
          color: '#007eff',
          textDecoration: 'underline'
        }}
      >

        https://github.com/thutasann/nextjs-ssr-sample
      </a>

      {
        todos.length === 0 ? (
          <div>Loading...</div>
        ): (
          todos.map(todo => (
            <div key={todo.id}>
              <p>
                {todo.id}: {todo.title}
              </p>
            </div>
          ))
        )
      }

    </div>
  )
}
